# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CloudletAgent/cloudlet_agent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CloudletAgent/cloudlet_agent.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\"CloudletAgent/cloudlet_agent.proto\")\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xf1\x01\n\x08\x43loudlet\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tcpu_cores\x18\x03 \x01(\r\x12\x15\n\rcpu_frequency\x18\x04 \x01(\x02\x12\x10\n\x08ram_size\x18\x05 \x01(\x04\x12\x10\n\x08rom_size\x18\x06 \x01(\x04\x12\n\n\x02os\x18\x07 \x01(\t\x12\x11\n\tos_kernel\x18\x08 \x01(\t\x12\n\n\x02ip\x18\t \x01(\t\x12\x10\n\x08latitude\x18\n \x01(\x01\x12\x11\n\tlongitude\x18\x0b \x01(\x01\x12\x0f\n\x07\x63ountry\x18\x0c \x01(\t\x12\x0e\n\x06region\x18\r \x01(\t\x12\x0c\n\x04\x63ity\x18\x0e \x01(\t\"\x89\x01\n\x14ResponseWithCloudlet\x12\x19\n\x06status\x18\x01 \x01(\x0b\x32\t.Response\x12\x1b\n\x08\x63loudlet\x18\x02 \x01(\x0b\x32\t.Cloudlet\x12\x1d\n\x15swarm_manager_address\x18\x03 \x01(\t\x12\x1a\n\x12swarm_worker_token\x18\x04 \x01(\t29\n\x0c\x43loudletsAPI\x12)\n\x03\x41\x64\x64\x12\t.Cloudlet\x1a\x15.ResponseWithCloudlet\"\x00\x62\x06proto3'
)




_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='Response.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=79,
)


_CLOUDLET = _descriptor.Descriptor(
  name='Cloudlet',
  full_name='Cloudlet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Cloudlet.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Cloudlet.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_cores', full_name='Cloudlet.cpu_cores', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_frequency', full_name='Cloudlet.cpu_frequency', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ram_size', full_name='Cloudlet.ram_size', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rom_size', full_name='Cloudlet.rom_size', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='os', full_name='Cloudlet.os', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='os_kernel', full_name='Cloudlet.os_kernel', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='Cloudlet.ip', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Cloudlet.latitude', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Cloudlet.longitude', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country', full_name='Cloudlet.country', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='region', full_name='Cloudlet.region', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='Cloudlet.city', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=323,
)


_RESPONSEWITHCLOUDLET = _descriptor.Descriptor(
  name='ResponseWithCloudlet',
  full_name='ResponseWithCloudlet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ResponseWithCloudlet.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cloudlet', full_name='ResponseWithCloudlet.cloudlet', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='swarm_manager_address', full_name='ResponseWithCloudlet.swarm_manager_address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='swarm_worker_token', full_name='ResponseWithCloudlet.swarm_worker_token', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=463,
)

_RESPONSEWITHCLOUDLET.fields_by_name['status'].message_type = _RESPONSE
_RESPONSEWITHCLOUDLET.fields_by_name['cloudlet'].message_type = _CLOUDLET
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Cloudlet'] = _CLOUDLET
DESCRIPTOR.message_types_by_name['ResponseWithCloudlet'] = _RESPONSEWITHCLOUDLET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'CloudletAgent.cloudlet_agent_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

Cloudlet = _reflection.GeneratedProtocolMessageType('Cloudlet', (_message.Message,), {
  'DESCRIPTOR' : _CLOUDLET,
  '__module__' : 'CloudletAgent.cloudlet_agent_pb2'
  # @@protoc_insertion_point(class_scope:Cloudlet)
  })
_sym_db.RegisterMessage(Cloudlet)

ResponseWithCloudlet = _reflection.GeneratedProtocolMessageType('ResponseWithCloudlet', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEWITHCLOUDLET,
  '__module__' : 'CloudletAgent.cloudlet_agent_pb2'
  # @@protoc_insertion_point(class_scope:ResponseWithCloudlet)
  })
_sym_db.RegisterMessage(ResponseWithCloudlet)



_CLOUDLETSAPI = _descriptor.ServiceDescriptor(
  name='CloudletsAPI',
  full_name='CloudletsAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=465,
  serialized_end=522,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='CloudletsAPI.Add',
    index=0,
    containing_service=None,
    input_type=_CLOUDLET,
    output_type=_RESPONSEWITHCLOUDLET,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLOUDLETSAPI)

DESCRIPTOR.services_by_name['CloudletsAPI'] = _CLOUDLETSAPI

# @@protoc_insertion_point(module_scope)
